development/project/config/routes.rb
Rails.application.routes.draw do
  
  get "search_parking/list_favorite/:user" => 'search_parking#list_favorite', :as => :list_favorite
  
  resources :search_parking do
    collection do
      get 'list_park'
    end
  end
  
  resources :search_parking do
    collection do
      post 'reserve'
    end
  end

  get 'search_parking/index'

  get 'welcome/index'

  resources :reservation_types
  devise_for :users
  resources :reservations
  resources :car_parks
  resources :favorites
  resources :districts
 root 'home#index'

end

development/project/app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :district
  
    #validacion
    validates :name ,presence: true
    validates :user ,presence: true
    validates :district ,presence: true
  
end

development/project/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout "home"
  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.all
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to @favorite, notice: 'Favorite was successfully created.' }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.require(:favorite).permit(:name, :user_id, :district_id)
    end
end

development/project/app/helpers/favorites_helper.rb
module FavoritesHelper
end

development/project/app/views/favorites/_form.html.erb
<%= simple_form_for @favorite, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.association :user, :include_blank => true %>
  <%= f.association :district, :include_blank => true %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                favorites_path, :class => 'btn btn-default' %>
<% end %>

development/project/app/views/favorites/edit.html.erb
<%- model_class = Favorite -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

development/project/app/views/favorites/index.html.erb
<%- model_class = Favorite -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:district_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= link_to favorite.id, favorite_path(favorite) %></td>
        <td><%= favorite.name %></td>
        <td><%= favorite.user_id %></td>
        <td><%= favorite.district_id %></td>
        <td><%=l favorite.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_favorite_path(favorite), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      favorite_path(favorite),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_favorite_path,
            :class => 'btn btn-primary' %>

development/project/app/views/favorites/new.html.erb
<%- model_class = Favorite -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

development/project/app/views/favorites/show.html.erb
<%- model_class = Favorite -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @favorite.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @favorite.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:district_id) %>:</strong></dt>
  <dd><%= @favorite.district_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              favorites_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_favorite_path(@favorite), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              favorite_path(@favorite),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>