development/project/config/routes.rb
Rails.application.routes.draw do
  
  get "search_parking/list_favorite/:user" => 'search_parking#list_favorite', :as => :list_favorite
  
  resources :search_parking do
    collection do
      get 'list_park'
    end
  end
  
  resources :search_parking do
    collection do
      post 'reserve'
    end
  end

  get 'search_parking/index'

  get 'welcome/index'

  resources :reservation_types
  devise_for :users
  resources :reservations
  resources :car_parks
  resources :favorites
  resources :districts
 root 'home#index'

end

development/project/app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :car_parks
  belongs_to :reservation_types
end

development/project/app/models/reservation_type.rb
class ReservationType < ActiveRecord::Base
    has_many :reservations
    has_many :car_parks
end

development/project/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout "home"
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:code, :started_at, :ended_at, :started_time, :ended_time, :user_id, :car_park_id)
    end
end

development/project/app/helpers/reservations_helper.rb
module ReservationsHelper
end

development/project/app/views/reservations/_form.html.erb
<%= simple_form_for @reservation, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  <%= f.input :code %>
  <%= f.input :started_at %>
  <%= f.input :ended_at %>
  <%= f.input :started_time %>
  <%= f.input :ended_time %>
  <%= f.input :user_id %>
  <%= f.input :car_park_id %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                reservations_path, :class => 'btn btn-default' %>
<% end %>

development/project/app/views/reservations/edit.html.erb
<%- model_class = Reservation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

development/project/app/views/reservations/index.html.erb
<%- model_class = Reservation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:started_at) %></th>
      <th><%= model_class.human_attribute_name(:ended_at) %></th>
      <th><%= model_class.human_attribute_name(:started_time) %></th>
      <th><%= model_class.human_attribute_name(:ended_time) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:car_park_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= link_to reservation.id, reservation_path(reservation) %></td>
        <td><%= reservation.code %></td>
        <td><%= reservation.started_at %></td>
        <td><%= reservation.ended_at %></td>
        <td><%= reservation.started_time %></td>
        <td><%= reservation.ended_time %></td>
        <td><%= reservation.user_id %></td>
        <td><%= reservation.car_park_id %></td>
        <td><%=l reservation.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_reservation_path(reservation), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      reservation_path(reservation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_reservation_path,
            :class => 'btn btn-primary' %>

development/project/app/views/reservations/new.html.erb
<%- model_class = Reservation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

development/project/app/views/reservations/show.html.erb
<%- model_class = Reservation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @reservation.code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:started_at) %>:</strong></dt>
  <dd><%= @reservation.started_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ended_at) %>:</strong></dt>
  <dd><%= @reservation.ended_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:started_time) %>:</strong></dt>
  <dd><%= @reservation.started_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ended_time) %>:</strong></dt>
  <dd><%= @reservation.ended_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @reservation.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:car_park_id) %>:</strong></dt>
  <dd><%= @reservation.car_park_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              reservations_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_reservation_path(@reservation), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              reservation_path(@reservation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>