development/project/config/routes.rb
Rails.application.routes.draw do
  
  get "search_parking/list_favorite/:user" => 'search_parking#list_favorite', :as => :list_favorite
  
  resources :search_parking do
    collection do
      get 'list_park'
    end
  end
  
  resources :search_parking do
    collection do
      post 'reserve'
    end
  end

  get 'search_parking/index'

  get 'welcome/index'

  resources :reservation_types
  devise_for :users
  resources :reservations
  resources :car_parks
  resources :favorites
  resources :districts
 root 'home#index'

end

development/project/app/controllers/reservation_types_controller.rb
class ReservationTypesController < ApplicationController
  before_action :set_reservation_type, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout "home"
  # GET /reservation_types
  # GET /reservation_types.json
  def index
    @reservation_types = ReservationType.all
  end

  # GET /reservation_types/1
  # GET /reservation_types/1.json
  def show
  end

  # GET /reservation_types/new
  def new
    @reservation_type = ReservationType.new
  end

  # GET /reservation_types/1/edit
  def edit
  end

  # POST /reservation_types
  # POST /reservation_types.json
  def create
    @reservation_type = ReservationType.new(reservation_type_params)

    respond_to do |format|
      if @reservation_type.save
        format.html { redirect_to @reservation_type, notice: 'Reservation type was successfully created.' }
        format.json { render :show, status: :created, location: @reservation_type }
      else
        format.html { render :new }
        format.json { render json: @reservation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservation_types/1
  # PATCH/PUT /reservation_types/1.json
  def update
    respond_to do |format|
      if @reservation_type.update(reservation_type_params)
        format.html { redirect_to @reservation_type, notice: 'Reservation type was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation_type }
      else
        format.html { render :edit }
        format.json { render json: @reservation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservation_types/1
  # DELETE /reservation_types/1.json
  def destroy
    @reservation_type.destroy
    respond_to do |format|
      format.html { redirect_to reservation_types_url, notice: 'Reservation type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation_type
      @reservation_type = ReservationType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_type_params
      params.require(:reservation_type).permit(:name, :description)
    end
end

development/project/app/helpers/reservation_types_helper.rb
module ReservationTypesHelper
end

development/project/app/views/reservation_types/_form.html.erb
<%= simple_form_for @reservation_type, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :description %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                reservation_types_path, :class => 'btn btn-default' %>
<% end %>

development/project/app/views/reservation_types/edit.html.erb
<%- model_class = ReservationType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

development/project/app/views/reservation_types/index.html.erb
<%- model_class = ReservationType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reservation_types.each do |reservation_type| %>
      <tr>
        <td><%= link_to reservation_type.id, reservation_type_path(reservation_type) %></td>
        <td><%= reservation_type.name %></td>
        <td><%= reservation_type.description %></td>
        <td><%=l reservation_type.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_reservation_type_path(reservation_type), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      reservation_type_path(reservation_type),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_reservation_type_path,
            :class => 'btn btn-primary' %>

development/project/app/views/reservation_types/new.html.erb
<%- model_class = ReservationType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

development/project/app/views/reservation_types/show.html.erb
<%- model_class = ReservationType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @reservation_type.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @reservation_type.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              reservation_types_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_reservation_type_path(@reservation_type), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              reservation_type_path(@reservation_type),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>