development/project/config/routes.rb
Rails.application.routes.draw do
  
  get "search_parking/list_favorite/:user" => 'search_parking#list_favorite', :as => :list_favorite
  
  resources :search_parking do
    collection do
      get 'list_park'
    end
  end
  
  resources :search_parking do
    collection do
      post 'reserve'
    end
  end

  get 'search_parking/index'

  get 'welcome/index'

  resources :reservation_types
  devise_for :users
  resources :reservations
  resources :car_parks
  resources :favorites
  resources :districts
 root 'home#index'

end

development/project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Project" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Insta Parking</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <!--<li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>-->
            <% if user_signed_in? %>
            <% else %>
                <li class="page-scroll">
                  <%= link_to "Sign In", new_user_session_path%>
                </li>
                <li class="page-scroll">
                  <%= link_to "Sign Up", new_user_registration_path %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

      <div>
        <div class="login">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

       <footer class="home-footer">
        <div  class="container">
          <p>&copy; Company 2016</p>
        </div>
      </footer>

  </body>
</html>

development/project/app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Project" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">
          <% if user_signed_in? %>
            <% if current_user.id == 1 %>
            SB Admin | <%= current_user.email%>
            <% else %>
            Insta Parking
            <% end %>
          <% else %>
          Insta Parking
          <% end %>
        </a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <% if current_user.id == 1 %>
                <li><%= link_to "Districts", "/districts"  %></li>
                <li><%= link_to "Resevations", "/reservations"  %></li>
                <li><%= link_to "Favorites", "/favorites"  %></li>
                <li><%= link_to "Resevations types", "/reservation_types"  %></li>
                <li><%= link_to "Car Parks", "/car_parks"  %></li>
                
              <% else %>
              
                <li class="page-scroll">
                  <%= link_to "Buscar Parqueo", search_parking_index_path%>
                </li>
                <li class="page-scroll">
                  <%= link_to "Ofertar parqueo", new_car_park_path %>
                </li>
                
              <% end %>
                
                <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.email%> <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                         
                          <li>
                            <% if user_signed_in? %>
                              
                              <%= link_to(destroy_user_session_path, :method => :delete, :class => '') do %>
                                <i class="fa fa-fw fa-power-off"> </i><span> Sign Out</span>
                              <% end %>
                            <% else %>
                              <a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                            <% end %>
                          </li>
                      </ul>
                  </li>
            <% else %>
                <li class="page-scroll">
                  <%= link_to "Nosotros", "#nosotros"  %>
                </li>
                <li class="page-scroll">
                  <%= link_to "Sign In", new_user_session_path%>
                </li>
                <li class="page-scroll">
                  <%= link_to "Sign Up", new_user_registration_path %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <% if user_signed_in? %>
      <% if current_user.id == 1 %>
        <div class="container-admin">
            <%= bootstrap_flash %>
            <%= yield %>
        </div>
      <% else %>
        <div>
            <%= bootstrap_flash %>
            <%= yield %>
        </div>
      <% end %>
    <% else %>
      <div>
            <%= bootstrap_flash %>
            <%= yield %>
        </div>
    <% end %>
    
    <footer class="home-footer">
      <footer class="container">
        <p>&copy; Company 2016</p>
      </footer>
    </div>


  </body>
</html>